# Generated by Django 3.0 on 2019-12-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes_locales', verbose_name='Foto')),
                ('alt', models.CharField(max_length=100, verbose_name='Alt')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Imagen local',
                'verbose_name_plural': 'Imagenes locales',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LocalizacionLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lng', models.FloatField(verbose_name='Longitud')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='iconos_locales', verbose_name='Icono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Localizacion local',
                'verbose_name_plural': 'Localizacion locales',
                'ordering': ['-created'],
            },
        ),
    ]
