# Generated by Django 3.0 on 2020-01-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes_locales', verbose_name='Foto')),
                ('alt', models.CharField(max_length=100, verbose_name='Alt')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Imagen del local',
                'verbose_name_plural': 'Imagenes de los locales',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=100, verbose_name='Razon social')),
                ('telefono', models.CharField(max_length=8, verbose_name='Telefono')),
                ('rut', models.BigIntegerField(verbose_name='Rut')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LocalizacionLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lng', models.FloatField(verbose_name='Longitud')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='iconos_locales', verbose_name='Icono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Localizacion del local',
                'verbose_name_plural': 'Localizacion de los locales',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LocalTrabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Local', to='locales.Local')),
            ],
            options={
                'verbose_name': 'Empleado del local',
                'verbose_name_plural': 'Empleados del local',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LocalTrabajadorServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('duracion', models.FloatField(verbose_name='Duracion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('localTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empleado', to='locales.LocalTrabajador')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Servicio', to='servicios.Servicio')),
            ],
            options={
                'verbose_name': 'Servicios que brinda el empleado del local',
                'verbose_name_plural': 'Servicios que brindan los empleados del local',
                'ordering': ['-created'],
            },
        ),
    ]
