# Generated by Django 3.0 on 2019-12-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locales', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTrabajador',
            fields=[
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Trabajador', serialize=False, to='usuarios.Trabajador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rol', to='usuarios.Rol')),
            ],
            options={
                'verbose_name': 'Local trabajador',
                'verbose_name_plural': 'Local trabajadores',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('razonSocial', models.CharField(max_length=100, verbose_name='Razon social')),
                ('telefono', models.CharField(max_length=8, verbose_name='Telefono')),
                ('rut', models.BigIntegerField(verbose_name='Rut')),
                ('localizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Localizacion', serialize=False, to='locales.LocalizacionLocal')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locales',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LocalTrabajadorServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(verbose_name='precio')),
                ('duracion', models.FloatField(verbose_name='duracion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('localTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LocalTrabajador', to='locales.LocalTrabajador')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Servicio', to='servicios.Servicio')),
            ],
            options={
                'verbose_name': 'Enlaze local-trabajador-servicio',
                'verbose_name_plural': 'Enlaze local-trabajador-servicio',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='localtrabajador',
            name='serviciosQuePuedeRealizar',
            field=models.ManyToManyField(related_name='LocalTrabajador', through='locales.LocalTrabajadorServicio', to='servicios.Servicio'),
        ),
        migrations.AddField(
            model_name='localtrabajador',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Local', to='locales.Local'),
        ),
        migrations.AddField(
            model_name='imagenlocal',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImagenLocal', to='locales.Local'),
        ),
    ]
