# Generated by Django 3.0 on 2020-01-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locales', '0001_initial'),
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtrabajador',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rol', to='usuarios.Rol'),
        ),
        migrations.AddField(
            model_name='localtrabajador',
            name='serviciosQuePuedeRealizar',
            field=models.ManyToManyField(related_name='LocalTrabajador', through='locales.LocalTrabajadorServicio', to='servicios.Servicio'),
        ),
        migrations.AddField(
            model_name='localtrabajador',
            name='trabajador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Trabajador', to='usuarios.Trabajador'),
        ),
        migrations.AddField(
            model_name='local',
            name='localizacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Localizacion', to='locales.LocalizacionLocal'),
        ),
        migrations.AddField(
            model_name='imagenlocal',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImagenLocal', to='locales.Local'),
        ),
    ]
