# Generated by Django 3.0 on 2020-01-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('locales', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTrabajador',
            fields=[
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Trabajador', serialize=False, to='usuarios.Trabajador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Local', to='locales.Local')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rol', to='usuarios.Rol')),
            ],
            options={
                'verbose_name': 'Empleado del local',
                'verbose_name_plural': 'Empleados del local',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LocalTrabajadorServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('duracion', models.FloatField(verbose_name='Duracion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('localTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empleado', to='locales.LocalTrabajador')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Servicio', to='servicios.Servicio')),
            ],
            options={
                'verbose_name': 'Servicios que brinda el empleado del local',
                'verbose_name_plural': 'Servicios que brindan los empleados del local',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='localtrabajador',
            name='serviciosQuePuedeRealizar',
            field=models.ManyToManyField(related_name='LocalTrabajador', through='locales.LocalTrabajadorServicio', to='servicios.Servicio'),
        ),
        migrations.AddField(
            model_name='local',
            name='localizacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Localizacion', to='locales.LocalizacionLocal'),
        ),
        migrations.AddField(
            model_name='imagenlocal',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImagenLocal', to='locales.Local'),
        ),
    ]
