# Generated by Django 3.0 on 2019-12-19 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_auto_20191218_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenlocal',
            options={'ordering': ['-created'], 'verbose_name': 'Imagen del local', 'verbose_name_plural': 'Imagenes de los locales'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ['-created'], 'verbose_name': 'Local', 'verbose_name_plural': 'Locales'},
        ),
        migrations.AlterModelOptions(
            name='localizacionlocal',
            options={'ordering': ['-created'], 'verbose_name': 'Localizacion del local', 'verbose_name_plural': 'Localizacion de los locales'},
        ),
        migrations.AlterModelOptions(
            name='localtrabajador',
            options={'ordering': ['-created'], 'verbose_name': 'Empleado del local', 'verbose_name_plural': 'Empleados del local'},
        ),
        migrations.AlterModelOptions(
            name='localtrabajadorservicio',
            options={'ordering': ['-created'], 'verbose_name': 'Servicios que brinda el empleado del local', 'verbose_name_plural': 'Servicios que brindan los empleados del local'},
        ),
        migrations.AlterField(
            model_name='localtrabajadorservicio',
            name='duracion',
            field=models.FloatField(verbose_name='Duracion'),
        ),
        migrations.AlterField(
            model_name='localtrabajadorservicio',
            name='localTrabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empleado', to='locales.LocalTrabajador'),
        ),
        migrations.AlterField(
            model_name='localtrabajadorservicio',
            name='precio',
            field=models.FloatField(verbose_name='Precio'),
        ),
    ]
