# Generated by Django 3.0 on 2019-12-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('locales', '0002_auto_20191218_1227'),
        ('usuarios', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionclienteempleadolocal',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atencion_cliente_empleado_local', to='locales.Local'),
        ),
        migrations.AddField(
            model_name='atencionclienteempleadolocal',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador_servicio_local_trabajador_servicio', to='usuarios.TrabajadorServicio'),
        ),
        migrations.AddField(
            model_name='atencionclienteempleadolocal',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atencion_cliente_empleado_local_trabajador', to='locales.LocalTrabajador'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='trabajadorservicio',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador_servicio', to='usuarios.Trabajador'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='servicios',
            field=models.ManyToManyField(related_name='trabajador_servicio', through='usuarios.TrabajadorServicio', to='servicios.Servicio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='atencionClienteEmpleadoLocal',
            field=models.ManyToManyField(related_name='tb_cliente_atencion_cliente_empleado_local', through='usuarios.AtencionClienteEmpleadoLocal', to='locales.Local'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='atencionClienteTrabajador',
            field=models.ManyToManyField(related_name='atencion_cliente_trabajador', through='usuarios.AtencionClienteTrabajador', to='usuarios.Trabajador'),
        ),
        migrations.AddField(
            model_name='atencionclientetrabajador',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atencion_cliente_trabajador_tb_atencion_cliente', to='usuarios.Cliente'),
        ),
        migrations.AddField(
            model_name='atencionclientetrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atecion_trabajador', to='usuarios.Trabajador'),
        ),
        migrations.AddField(
            model_name='atencionclienteempleadolocal',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atencion_cliente_empleado_local_tb_atencion_cliente', to='usuarios.Cliente'),
        ),
    ]
