# Generated by Django 3.0 on 2019-12-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20191218_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atencionclienteempleadolocal',
            options={'ordering': ['-created'], 'verbose_name': 'Atencion del cliente con el empleado en el local', 'verbose_name_plural': 'Atenciones de los clientes con los empleados en el local'},
        ),
        migrations.AlterModelOptions(
            name='atencionclientetrabajador',
            options={'ordering': ['-created'], 'verbose_name': 'Atencion del cliente con el trabajador independiente', 'verbose_name_plural': 'Atencion de los clientes con los trabajadores independientes'},
        ),
    ]
